//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.14 at 08:34:41 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mednov.org/wsdl_csv/web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mednov.wsdl_csv.web_service;
